[feat] WYBLabelEditText CustomView 구현
0-Crew/WYB_Android pull request #5
Opened 2022-03-22 09:56 UTC by ymcho24

## 📝 Changes
- '챌린지 오픈', '설정 - 닉네임 변경', '회원가입 - 닉네임 설정'에 공통적으로 쓰이는 위젯인 **label 이 포함된 `CustomEditText`** 를 구현했습니다.
- `backgroundStroke` 속성을 통해 박스의 테두리 색상을 지정합니다. (option: `orange`/`gray`)
- `labelText` 속성을 통해 좌측 상단에 작은 글씨로 들어가는 label 의 문구를 작성합니다.
- `iconType` 속성을 통해 우측 하단 아이콘의 종류를 변경합니다. (option: `edit`/`check`)
- `showIcon` 속성을 통해 우측 하단 아이콘의 visibility 를 조절합니다.
- `WYBLabelEditText.kt` 의 `setTextFilter` 함수는 해당 EditText 에 **입력할 수 있는 최대 글자 수**와 **입력 가능한 문자의 종류**를 매개변수로 받아 `InputFilter` 로 적용해주는 역할을 하고 있습니다.

## 📷 Screenshot
| 기능 | 스크린샷 |
| ----- | :------------------------------: | 
| 화면 | <img src="https://user-images.githubusercontent.com/52772787/159453219-948b6c87-088b-420c-b416-8be55ab840f9.png" width="400" /> |
| 코드 | <img src="https://user-images.githubusercontent.com/52772787/159452364-21d7d07d-f4ec-4ae3-88f8-30fbc4f4829b.png" width="400" /> |

## 💬 Comment
- values/attrs.xml 파일을 새로 생성했습니다!

2022-03-22 10:04 UTC, ymcho24 commented on app/src/main/res/drawable/ic_check.xml
> +</vector>
<img width="169" alt="스크린샷 2022-03-22 오후 6 58 21" src="https://user-images.githubusercontent.com/52772787/159455134-dccc46de-1aab-4c82-99b9-5f4331dd5c4b.png">

우리가 사용하고 있는 아이콘들이 대부분 모양은 같은데 색상이 다른 경우가 많더라고요!! 각 색상마다 아이콘을 다운받는 것도 좋지만, 조금 더 효율적으로 리소스 파일들을 관리하기 위해서는 모양이 같은 아이콘들은 svg 로 export 받아서 `vector asset` 으로 만들어주면 여러 색상을 덧입혀서 재사용이 가능합니다!! 이 때 생성된 `vector asset` 파일 (`ic_check.xml`) 의 `fillColor` 나 `strokeColor` 를 모두 **#000000** 으로 맞춰주면, 나중에 이 `vector asset` 파일을 `ImageView` 의 `src` 로 사용할 때 `app:tint="orange"` 속성을 추가해서 색상을 자유롭게 변경할 수 있습니다!!

2022-03-22 10:05 UTC, ymcho24 commented on app/src/main/res/layout/view_wyb_label_edit_text.xml
> +            tools:src="@drawable/ic_edit" />
위에서 말한 `app:tint` 속성이 사용된 예시입니다!!

2022-03-22 10:15 UTC, ymcho24 reviewed
**💡 커스텀 뷰 만들기 간단 요약!**

2022-03-22 10:15 UTC, ymcho24 commented on app/src/main/res/layout/view_wyb_label_edit_text.xml
> +    tools:background="@drawable/shape_gray_2_stroke">
1. 공통되는 부분의 레이아웃을 만들어줍니다. 각 위젯마다 id도 꼭 지정해주세요!

2022-03-22 10:15 UTC, ymcho24 commented on app/src/main/res/values/attrs.xml
> +</resources>
2. `values/attrs.xml` 파일에 이 `CustomView` 에서 사용할 속성을 추가해 줍니다. 아까 레이아웃 파일에서는 커스텀 뷰로 묶일 여러 뷰들의 공통적인 기능들이 모두 들어가도록 했다면, 이 `attrs` 파일에서는 각 뷰의 서로 다른 디테일들을 잡아내기 위한 속성을 추가해주면 됩니다!

2022-03-22 10:15 UTC, ymcho24 commented on app/src/main/java/com/wyb/wyb_android/widget/WYBLabelEditText.kt
> +) : LinearLayout(context, attrs) {
3. `widget/WYBLabelEditText.kt` 파일에서는 `values/attrs.xml` 에서 새롭게 추가한 속성들을 정의해주고, 해당 뷰가 공통적으로 가지고 있는 기능들을 전역 함수로 구현합니다. (이 함수들은 후에 해당 커스텀 뷰를 사용하는 `activity` 나 `fragment` 에서 사용 가능합니다!)

2022-03-23 15:11 UTC, gaeun23 requested changes

2022-03-23 15:11 UTC, gaeun23 commented on app/src/main/res/drawable/shape_gray_2_stroke.xml
> +        android:color="@color/gray_2" />
gray_2 색상이 사용되어서 `shape_gray_2_stroke` 라고 붙인 건가용 ?  추후에 동일한 색상코드에 radius 값이나 width 값이 있는 drawble이 추가되면 id 읽기가 살짝쿵 헷갈릴 수 도 있을 것 같아요! 색상코드는 지정된 값이니 ` shape_gray2_stroke`라고 사용하는 건 어떨까요 ?>ㅁ<

2022-03-23 15:11 UTC, gaeun23 commented on app/src/main/res/layout/view_wyb_label_edit_text.xml
> +            android:layout_width="20dp"
Vector는 asset 속성에서 크기값을 지정해주고 있는데, imageView에서 사용할 때도 width/height에 특정 dp 값을 지정해야 하는 단점아닌 단점이 있네요 ,, 😌 테스트해보니 (imageView에서 자주 사용하는) wrap_content 속성을 사용하면 크기가 달라져 보이니 주의해서 사용하겠슴니다 !-!
```
    android:width="20dp"
    android:height="20dp"
    android:viewportWidth="20"
    android:viewportHeight="20">
```

2022-03-23 15:11 UTC, gaeun23 commented on app/src/main/res/values/strings.xml
> +    <string name="challenge_open_comport_label">편리함</string>
[의견] 워유보 앱 특성상 "편리함", "불편함" 단어는 앱 내에서 자주 사용하게 될 것 같아서 general 로 묶는 건 어떨까요?

2022-03-23 15:14 UTC, gaeun23 commented on app/src/main/res/drawable/ic_check.xml
> +</vector>
오 !! 이 방법 너무 좋아요 ~ vector asset을 사용하게 되면 이미지가 잘 깨지지도 않을 것 같고 색상 표현도 더욱 정확히 할 수 있겠군요!!

2022-03-23 15:17 UTC, gaeun23 commented on app/src/main/res/drawable/ic_check.xml
> +</vector>
제플린을 보니 아이콘 중에 동일한 색상에, 사이즈만 다른 아이콘들이 있는 것 같아요! ! 이러한 경우 아이콘 id 값을 `ic_check_20` 이라고 명칭하면 직관적으로 확인할 수 있을 것 같아요~! 앱 내에서 사용한 모든 아이콘은 제플린>Style Guide에서 모두 확인할 수 있으니 id 명명하기 전에 한 번씩 확인하면 좋을 것 같아요!

2022-03-23 15:21 UTC, gaeun23 commented on app/src/main/java/com/wyb/wyb_android/widget/WYBLabelEditText.kt
> +        ViewWybLabelEditTextBinding.inflate(LayoutInflater.from(context), this, false)
커스텀 뷰에서도 binding을 사용할 수 있었군요 !! 너무 멋져요 ...✨ 꼼꼼히 읽어봤는데 깔끔하게 잘 만든 것 같아요! text pattern 속성도 체크할 수 있게 하다니 ~ 정말 디테일 합니다 고생많았아요 히온 ~~

2022-03-23 15:25 UTC, ymcho24 commented on app/src/main/res/drawable/ic_check.xml
> +</vector>
오 그럼 동일한 모양인데 사이즈가 여러개인 아이콘들은 모두 파일명 뒤에 사이즈를 붙일까요?! 그럼 지금 푸쉬한 파일에 속해있는 아이콘들도 확인해서 파일명 수정할게요!

2022-03-23 15:28 UTC, ymcho24 commented on app/src/main/res/drawable/shape_gray_2_stroke.xml
> +        android:color="@color/gray_2" />
오 그렇네요! gray_2 라고 이름 붙였던 건 1 width 굵기의 gray_4 색상을 사용한 stroke drawable 이 메인에서 사용될 것 같아서, 이것과 구분하려고 색상 코드 값을 더 자세히 썼습니다! 위에 벡터 파일 이름 수정하면서 이것도 같이 수정할게요~!

2022-03-23 15:29 UTC, ymcho24 commented on app/src/main/res/values/strings.xml
> +    <string name="challenge_open_comport_label">편리함</string>
좋습니다!

2022-03-23 15:31 UTC, gaeun23 commented on app/src/main/res/drawable/shape_gray_2_stroke.xml
> +        android:color="@color/gray_2" />
네 좋아요 ~!

2022-03-23 15:54 UTC, gaeun23 approved these changes

2022-03-23 15:57 UTC, merged